const ALTERNATE_AND_SIMILAR_NAMES = {
  "abaddon": "abaddon",
  "abaddom": "abaddon",
  "abadon": "abaddon",
  "abadom": "abaddon",
  "abbaddon": "abaddon",
  "abbaddom": "abaddon",
  "abbadon": "abaddon",
  "abbadom": "abaddon",

  "alchemist": "alchemist",
  "alch": "alchemist",
  "alchemista": "alchemist",
  "alquemist": "alchemist",
  "alquemista": "alchemist",

  "ancient-apparition": "ancient-apparition",
  "anciente-apparition": "ancient-apparition",
  "ancientapparition": "ancient-apparition",
  "ancienteapparition": "ancient-apparition",
  "ancient apparition": "ancient-apparition",
  "anciente apparition": "ancient-apparition",
  "aa": "ancient-apparition",
  "ancient": "ancient-apparition",

  "anti-mage": "anti-mage",
  "antimage": "anti-mage",
  "anti mage": "anti-mage",
  "magina": "anti-mage",

  "arc-warden": "arc-warden",
  "arcwarden": "arc-warden",
  "arc warden": "arc-warden",
  "arc": "arc-warden",

  "axe": "axe",
  "axé": "axe",

  "bane": "bane",
  "bane elemental": "bane",
  "baneelemental": "bane",
  "bane-elemental": "bane",

  "batrider": "batrider",
  "bat rider": "batrider",
  "bat-rider": "batrider",
  "Jin\'zakk": "batrider",

  "beastmaster": "beastmaster",
  "beast master": "beastmaster",
  "beast-master": "beastmaster",
  "rexxar": "beastmaster",
  "rexar": "beastmaster",
  "hexxar": "beastmaster",
  "hexar": "beastmaster",

  "bloodseeker": "bloodseeker",
  "blood": "bloodseeker",
  "bloode": "bloodseeker",
  "bloodi": "bloodseeker",
  "blodi": "bloodseeker",
  "blode": "bloodseeker",

  "bounty-hunter": "bounty-hunter",
  "bountyhunter": "bounty-hunter",
  "bounty hunter": "bounty-hunter",
  "bounty": "bounty-hunter",
  "bh": "bounty-hunter",
  "gondar": "bounty-hunter",

  "brewmaster": "brewmaster",
  "brew master": "brewmaster",
  "brew-master": "brewmaster",
  "brew": "brewmaster",
  "briu": "brewmaster",
  "brio": "brewmaster",
  "mangix": "brewmaster",

  "bristleback": "bristleback",
  "bristle back": "bristleback",
  "bristle-back": "bristleback",
  "bristle": "bristleback",
  "bristol": "bristleback",
  "bristou": "bristleback",
  "bristóu": "bristleback",

  "broodmother": "broodmother",
  "brood mother": "broodmother",
  "brood-mother": "broodmother",
  "brood": "broodmother",
  "brôdi": "broodmother",
  "brudi": "broodmother",
  "black arachnia": "broodmother",
  "black-arachnia": "broodmother",
  "blackarachnia": "broodmother",

  "centaur-warrunner": "centaur-warrunner",
  "centaur warrunner": "centaur-warrunner",
  "centaurwarrunner": "centaur-warrunner",
  "centaur": "centaur-warrunner",
  "warrunner": "centaur-warrunner",
  "centaur": "centaur-warrunner",
  "centauro": "centaur-warrunner",
  "cent": "centaur-warrunner",

  "chaos-knight": "chaos-knight",
  "chaosknight": "chaos-knight",
  "chaos knight": "chaos-knight",
  "chaos": "chaos-knight",
  "ck": "chaos-knight",

  "chen": "chen",
  "chem": "chen",
  "xem": "chen",
  "xen": "chen",

  "clinkz": "clinkz",
  "clinks": "clinkz",
  "clinquis": "clinkz",
  "clinquiz": "clinkz",
  "bone fletcher": "clinkz",
  "bonefletcher": "clinkz",
  "bone-fletcher": "clinkz",
  "bone": "clinkz",

  "clockwerk": "clockwerk",
  "clock werk": "clockwerk",
  "clock-werk": "clockwerk",
  "clock": "clockwerk",
  "rattletrap": "clockwerk",
  "rattle trap": "clockwerk",
  "rattle-trap": "clockwerk",

  "crystal-maiden": "crystal-maiden",
  "crystal-meiden": "crystal-maiden",
  "crystal-meidem": "crystal-maiden",
  "cristal-maiden": "crystal-maiden",
  "cristal-meiden": "crystal-maiden",
  "cristal-meidem": "crystal-maiden",
  "crystal maiden": "crystal-maiden",
  "cristal maiden": "crystal-maiden",
  "cristal maidem": "crystal-maiden",
  "cristal meiden": "crystal-maiden",
  "cristal meidem": "crystal-maiden",
  "crystalmaiden": "crystal-maiden",
  "cristalmaiden": "crystal-maiden",
  "cristal": "crystal-maiden",
  "crystal": "crystal-maiden",
  "maiden": "crystal-maiden",
  "meiden": "crystal-maiden",
  "meidem": "crystal-maiden",
  "rilai": "crystal-maiden",
  "rylai": "crystal-maiden",
  "rylay": "crystal-maiden",
  "rilay": "crystal-maiden",

  "dark-seer": "dark-seer",
  "dark-sir": "dark-seer",
  "darkseer": "dark-seer",
  "darksir": "dark-seer",
  "dark seer": "dark-seer",
  "dark sir": "dark-seer",
  "ds": "dark-seer",

  "dark-willow": "dark-willow",
  "darkwillow": "dark-willow",
  "dark willow": "dark-willow",
  "dw": "dark-willow",

  "dawnbreaker": "dawnbreaker",
  "dawn breaker": "dawnbreaker",
  "dawnbreaker": "dawnbreaker",
  "dawn": "dawnbreaker",
  "db": "dawnbreaker",

  "dazzle": "dazzle",
  "dezzle": "dazzle",
  "dezel": "dazzle",
  "dezzel": "dazzle",
  "dezeu": "dazzle",
  "dezzeu": "dazzle",

  "death-prophet": "death-prophet",
  "deathprophet": "death-prophet",
  "death prophet": "death-prophet",
  "krobelus": "death-prophet",
  "crobelus": "death-prophet",
  "dp": "death-prophet",

  "disruptor": "disruptor",
  "disrupitor": "disruptor",
  "stormcrafter": "disruptor",
  "thrall": "disruptor",

  "doom": "doom",
  "doon": "doom",
  "dum": "doom",
  "dun": "doom",
  "lucifer": "doom",

  "dragon-knight": "dragon-knight",
  "dragonknight": "dragon-knight",
  "dragon knight": "dragon-knight",
  "dk": "dragon-knight",
  "davion": "dragon-knight",
  "slyrak": "dragon-knight",

  "drow-ranger": "drow-ranger",
  "drowranger": "drow-ranger",
  "drow ranger": "drow-ranger",
  "drow": "drow-ranger",
  "drou": "drow-ranger",
  "drol": "drow-ranger",
  "traxex": "drow-ranger",

  "earth-spirit": "earth-spirit",
  "earthspirit": "earth-spirit",
  "earth spirit": "earth-spirit",
  "earth": "earth-spirit",

  "earthshaker": "earthshaker",
  "earth shaker": "earthshaker",
  "earth-shaker": "earthshaker",
  "earth": "earthshaker",
  "shaker": "earthshaker",
  "raigor": "earthshaker",

  "elder-titan": "elder-titan",
  "eldertitan": "elder-titan",
  "elder titan": "elder-titan",
  "elder": "elder-titan",
  "et": "elder-titan",

  "ember-spirit": "ember-spirit",
  "emberspirit": "ember-spirit",
  "ember spirit": "ember-spirit",
  "ember": "ember-spirit",

  "enchantress": "enchantress",
  "enchantres": "enchantress",
  "encantress": "enchantress",
  "encantres": "enchantress",
  "aiushtha": "enchantress",

  "enigma": "enigma",

  "faceless-void": "faceless-void",
  "facelessvoid": "faceless-void",
  "faceless void": "faceless-void",
  "void": "faceless-void",
  "faceless": "faceless-void",

  "grimstroke": "grimstroke",
  "grim stroke": "grimstroke",
  "grim-stroke": "grimstroke",
  "grim": "grimstroke",

  "gyro copter": "gyrocopter",
  "girocopter": "gyrocopter",
  "giro copter": "gyrocopter",
  "gyro-copter": "gyrocopter",
  "giro-copter": "gyrocopter",
  "giro": "gyrocopter",
  "gyro": "gyrocopter",

  "hoodwink": "hoodwink",
  "hood": "hoodwink",
  "rudiwink": "hoodwink",
  "rudi": "hoodwink",
  "hodwink": "hoodwink",

  "huskar": "huskar",
  "huscar": "huskar",
  "ruskar": "huskar",
  "ruscar": "huskar",

  "invoker": "invoker",
  "carl": "invoker",
  "karl": "invoker",
  "invocador": "invoker",

  "io": "io",

  "jakiro": "jakiro",
  "jaquiro": "jakiro",

  "juggernaut": "juggernaut",
  "jugger": "juggernaut",
  "jugg": "juggernaut",
  "jug": "juggernaut",
  "yurnero": "juggernaut",
  "iurnero": "juggernaut",

  "keeper-of-the-light": "keeper-of-the-light",
  "keeperofthelight": "keeper-of-the-light",
  "keeper of the light": "keeper-of-the-light",
  "keeper": "keeper-of-the-light",
  "kotl": "keeper-of-the-light",
  "ezalor": "keeper-of-the-light",

  "kunkka": "kunkka",
  "cunkka": "kunkka",
  "kuncca": "kunkka",
  "cuncca": "kunkka",
  "kunka": "kunkka",
  "cunka": "kunkka",
  "kunca": "kunkka",
  "cunca": "kunkka",

  "legion-commander": "legion-commander",
  "legioncommander": "legion-commander",
  "legion commander": "legion-commander",
  "legion": "legion-commander",
  "legiao": "legion-commander",

  "leshrac": "leshrac",
  "lechrac": "leshrac",
  "leshirac": "leshrac",
  "lechirac": "leshrac",
  "lesh": "leshrac",
  "lech": "leshrac",

  "lich": "lich",
  "lichi": "lich",
  "liti": "lich",
  "lite": "lich",

  "lifestealer": "lifestealer",
  "life stealer": "lifestealer",
  "life-stealer": "lifestealer",
  "life": "lifestealer",
  "naix": "lifestealer",

  "lina": "lina",

  "lion": "lion",
  "laion": "lion",
  "leao": "lion",

  "lone-druid": "lone-druid",
  "lonedruid": "lone-druid",
  "lone druid": "lone-druid",
  "druid": "lone-druid",
  "lone": "lone-druid",

  "luna": "luna",

  "lycan": "lycan",
  "lican": "lycan",
  "laican": "lycan",
  "laycan": "lycan",

  "magnus": "magnus",
  "maguinus": "magnus",

  "marci": "marci",

  "mars": "mars",

  "medusa": "medusa",
  "meduza": "medusa",

  "meepo": "meepo",
  "mepo": "meepo",
  "mipo": "meepo",

  "mirana": "mirana",
  "miranda": "mirana",

  "monkey-king": "monkey-king",
  "monkeyking": "monkey-king",
  "monkey king": "monkey-king",
  "monkey": "monkey-king",
  "mk": "monkey-king",
  "simio": "monkey-king",

  "morphling": "morphling",
  "morph ling": "morphling",
  "morph-ling": "morphling",
  "morph": "morphling",
  "morfling": "morphling",

  "naga-siren": "naga-siren",
  "naga-sairen": "naga-siren",
  "nagasiren": "naga-siren",
  "nagasairen": "naga-siren",
  "naga siren": "naga-siren",
  "naga sairen": "naga-siren",
  "naga": "naga-siren",

  "natures-prophet": "natures-prophet",
  "nature-prophet": "natures-prophet",
  "naturesprophet": "natures-prophet",
  "natureprophet": "natures-prophet",
  "natures prophet": "natures-prophet",
  "nature prophet": "natures-prophet",
  "nature": "natures-prophet",
  "furion": "natures-prophet",

  "necrophos": "necrophos",
  "necro": "necrophos",
  "necrofos": "necrophos",
  "necromante": "necrophos",

  "night-stalker": "night-stalker",
  "nightstalker": "night-stalker",
  "night stalker": "night-stalker",
  "balanar": "night-stalker",
  "bala": "night-stalker",

  "nyx-assassin": "nyx-assassin",
  "nix-assassin": "nyx-assassin",
  "nyxassassin": "nyx-assassin",
  "nixassassin": "nyx-assassin",
  "nyx assassin": "nyx-assassin",
  "nix assassin": "nyx-assassin",
  "nyx": "nyx-assassin",
  "nix": "nyx-assassin",

  "ogre-magi": "ogre-magi",
  "ogremagi": "ogre-magi",
  "ogre magi": "ogre-magi",
  "ogre": "ogre-magi",
  "mago ogro": "ogre-magi",

  "omniknight": "omniknight",
  "omni knight": "omniknight",
  "omni-knight": "omniknight",
  "omni": "omniknight",
  "ok": "omniknight",

  "oracle": "oracle",
  "oraculo": "oracle",

  "outworld-devourer": "outworld-devourer",
  "outworlddevourer": "outworld-devourer",
  "outworld devourer": "outworld-devourer",
  "devourer": "outworld-devourer",
  "outworld": "outworld-devourer",
  "od": "outworld-devourer",

  "pangolier": "pangolier",
  "pango": "pangolier",

  "phantom-assassin": "phantom-assassin",
  "phanton-assassin": "phantom-assassin",
  "phantomassassin": "phantom-assassin",
  "phantonassassin": "phantom-assassin",
  "phantom assassin": "phantom-assassin",
  "phanton assassin": "phantom-assassin",
  "phantom": "phantom-assassin",
  "phanton": "phantom-assassin",
  "pa": "phantom-assassin",
  "mortred": "phantom-assassin",

  "phantom-lancer": "phantom-lancer",
  "phanton-lancer": "phantom-lancer",
  "phantomlancer": "phantom-lancer",
  "phantonlancer": "phantom-lancer",
  "phantom lancer": "phantom-lancer",
  "phanton lancer": "phantom-lancer",
  "pl": "phantom-lancer",

  "phoenix": "phoenix",
  "fenix": "phoenix",

  "primal-beast": "primal-beast",
  "primal beast": "primal-beast",
  "primal": "primal-beast",
  "fera": "primal-beast",
  "besta": "primal-beast",
  "beast": "primal-beast",
  "praimal": "primal-beast",
  "praimal beast": "primal-beast",
  "praimal-beast": "primal-beast",

  "puck": "puck",
  "puq": "puck",
  "puqui": "puck",
  "puque": "puck",

  "pudge": "pudge",
  "pude": "pudge",
  "pudi": "pudge",
  "pudao": "pudge",

  "pugna": "pugna",
  "puguina": "pugna",
  "oblivion": "pugna",

  "queen-of-pain": "queen-of-pain",
  "queen of pain": "queen-of-pain",
  "queenofpain": "queen-of-pain",
  "queen": "queen-of-pain",
  "qop": "queen-of-pain",
  "akasha": "queen-of-pain",
  "acasha": "queen-of-pain",

  "razor": "razor",
  "reizor": "razor",
  "gillette": "razor",
  "gilette": "razor",
  "gillete": "razor",
  "gilete": "razor",

  "riki": "riki",
  "rikimaru": "riki",
  "stealth assassin": "riki",
  "stealth-assassin": "riki",
  "stealthassassin": "riki",

  "rubick": "rubick",

  "sand-king": "sand-king",
  "sandking": "sand-king",
  "sand king": "sand-king",
  "sk": "sand-king",

  "shadow-demon": "shadow-demon",
  "shadowdemon": "shadow-demon",
  "shadow demon": "shadow-demon",

  "shadow-fiend": "shadow-fiend",
  "shadowfiend": "shadow-fiend",
  "shadow fiend": "shadow-fiend",
  "nevermore": "shadow-fiend",
  "never": "shadow-fiend",

  "shadow-shaman": "shadow-shaman",
  "shadowshaman": "shadow-shaman",
  "shadow shaman": "shadow-shaman",
  "ss": "shadow-shaman",
  "rasta": "shadow-shaman",
  "rhasta": "shadow-shaman",

  "silencer": "silencer",
  "silence": "silencer",

  "skywrath-mage": "skywrath-mage",
  "skywrathmage": "skywrath-mage",
  "skywrath": "skywrath-mage",
  "sky": "skywrath-mage",

  "slardar": "slardar",

  "slark": "slark",
  "nightcrawler": "slark",
  "murlocnightcrawler": "slark",
  "murloc nightcrawler": "slark",
  "murloc-nightcrawler": "slark",
  "murloc": "slark",

  "snapfire": "snapfire",
  "snap fire": "snapfire",
  "snap-fire": "snapfire",
  "vovo": "snapfire",
  "vovó": "snapfire",

  "sniper": "sniper",
  "snaiper": "sniper",

  "spectre": "spectre",

  "spirit-breaker": "spirit-breaker",
  "spiritbreaker": "spirit-breaker",
  "spirit breaker": "spirit-breaker",
  "sb": "spirit-breaker",
  "barathrum": "spirit-breaker",
  "baratum": "spirit-breaker",
  "barathum": "spirit-breaker",
  "bara": "spirit-breaker",

  "storm-spirit": "storm-spirit",
  "stormspirit": "storm-spirit",
  "storm spirit": "storm-spirit",
  "storm": "storm-spirit",

  "sven": "sven",

  "techies": "techies",

  "templar-assassin": "templar-assassin",
  "templarassassin": "templar-assassin",
  "templar assassin": "templar-assassin",
  "templar": "templar-assassin",
  "lanaya": "templar-assassin",
  "lanaia": "templar-assassin",

  "terrorblade": "terrorblade",
  "terror blade": "terrorblade",
  "terror-blade": "terrorblade",
  "terror": "terrorblade",

  "tidehunter": "tidehunter",
  "tide": "tidehunter",
  "taide": "tidehunter",
  "taidehunter": "tidehunter",

  "timbersaw": "timbersaw",
  "timber saw": "timbersaw",
  "timber-saw": "timbersaw",
  "timber": "timbersaw",

  "tinker": "tinker",
  "tinquer": "tinker",

  "tiny": "tiny",
  "tine": "tiny",
  "tini": "tiny",

  "treant-protector": "treant-protector",
  "treantprotector": "treant-protector",
  "treant protector": "treant-protector",
  "treant": "treant-protector",
  "arvore": "treant-protector",

  "troll-warlord": "troll-warlord",
  "trollwarlord": "troll-warlord",
  "troll warlord": "troll-warlord",
  "troll": "troll-warlord",

  "tusk": "tusk",

  "underlord": "underlord",
  "pit lord": "underlord",
  "pit-lord": "underlord",
  "pitlord": "underlord",
  "pit": "underlord",

  "undying": "undying",
  "undiing": "undying",

  "ursa": "ursa",

  "vengeful-spirit": "vengeful-spirit",
  "vengefulspirit": "vengeful-spirit",
  "vengeful spirit": "vengeful-spirit",
  "vengeful": "vengeful-spirit",
  "venge": "vengeful-spirit",

  "venomancer": "venomancer",
  "veno mancer": "venomancer",
  "veno-mancer": "venomancer",
  "veno": "venomancer",

  "viper": "viper",
  "vaiper": "viper",

  "visage": "visage",
  "vizage": "visage",

  "void-spirit": "void-spirit",
  "voidspirit": "void-spirit",
  "void spirit": "void-spirit",

  "warlock": "warlock",

  "weaver": "weaver",
  "weever": "weaver",

  "windranger": "windranger",
  "wind ranger": "windranger",
  "wind-ranger": "windranger",
  "wind": "windranger",

  "winter-wyvern": "winter-wyvern",
  "winterwyvern": "winter-wyvern",
  "winter": "winter-wyvern",
  "ww": "winter-wyvern",

  "witch-doctor": "witch-doctor",
  "witchdoctor": "witch-doctor",
  "witch doctor": "witch-doctor",
  "witch": "witch-doctor",

  "wraith-king": "wraith-king",
  "wraithking": "wraith-king",
  "wraith king": "wraith-king",
  "wk": "wraith-king",

  "zeus": "zeus"

}

module.exports = ALTERNATE_AND_SIMILAR_NAMES;